sudo: required
services:
  - docker
  

before_install:
  - docker build -t stevezmac/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stevezmac/docker-react npm run test -- --watchAll=false
